version: '3'
services:
  node_app_factory:
    container_name: node_app_factory
    build: nodejs
    volumes:
      - ./nodejs/workspace:/root/workspace
  ruby_app_factory:
    container_name: ruby_app_factory
    build: ruby
#    command: "tail -n 1 -f emptyfile_for_keeping_container_alive"
    volumes:
      - ./ruby/workspace:/root/workspace