version: '3'
services:
  node_app_factory:
    container_name: node_app_factory
    build: .
    command: "tail -n 1 -f emptyfile_for_keeping_container_alive"
    volumes:
      - ./workspace:/root/workspace